workflows:
  ios_build:
    name: "Build iOS Debug"
    environment:
      xcode: "13.3"
    scripts:
      - xcodebuild -workspace yourproject.xcworkspace -scheme yourproject -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' -configuration Debug clean build
    artifacts:
      - build/ios/**/*.ipa
