workflows:
  ios-workflow:
      name: iOS Workflow
      instance_type: mac_mini_m1
      environment:
        xcode: 13.4.1
      scripts:
        - name: Build app for testing
          script: |
            set -ex

            flutter build ios integration_test/app_test.dart --release

            cd ios
            xcodebuild \
              -workspace Runner.xcworkspace \
              -scheme Runner \
              -config Flutter/Release.xcconfig \
              -derivedDataPath "../build/ios_integ" \
              -sdk iphoneos \
              build-for-testing
        - name: Package tests bundle
          script: |
            set -ex
            cd ./build/ios_integ/Build/Products
            zip -r "ios_tests.zip" *-iphoneos *.xctestrun
        - name: Run tests in Firebase Test Lab
          script: gcloud firebase test ios run --test "build/ios_integ/Build/Products/ios_tests.zip"     
      artifacts:
        - "**/ios_tests.zip"
